### ISSUE TITLE
Feature Request: r2ghidra decompiler

### ISSUE THREAD

**Issue by cielonet** [br0kej/bin2ml#12]
Is there a way to add a decompiling feature to the tool so that it leverages radare2 plugin to, say decompile functions. In addition to having the ESIL representation norm/non-norm I would like to have the decompiled function code alongside.

Right now, I am using pandas to read the esil json files of functions and test various models to see how well they are performing similarity search's (e.g. cosine similarity, etc.) between various versions of the same function.  But I would like to also have the ability to import into pandas alongside the ESIL the functions decompiled pseudocode in order to perform similar semantic evaluations.

Not sure if this is within the intended scope of this tool. Great tool either way very useful in many ways.
Reference:
[r2ghidra](https://github.com/radareorg/r2ghidra)

**Comment by br0kej** [comment]
Thank you for the feature suggestion @cielonet. I will have a look into it 👍🏼

**Comment by cielonet** [comment]
Hey thank you for this. I just saw this. Been so busy with a million things. Will be testing within the next few weeks. Thanks again!

**Comment by br0kej** [comment]
It's probably worth mentioning - There are a few tweaks to how the data is outputted on `dev`. It might be worth building the `dev` version if you are brave enough and having a go with that :)
