### ISSUE TITLE
Formating error when generating esil

### ISSUE THREAD

**Issue by cielonet** [br0kej/bin2ml#8]
This was a "dumb user" error because I passed not an extracted file but the original file. Perhaps an error msg letting folks know this is not the valid .json file needed.

```
bin2ml generate nlp --path <file.so> --instruction-type esil --data-out-path . --output-format <single || funcstring>
thread 'main' panicked at src/files.rs:61:51:
Unable to read file: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Also if I put an invalid json I get an error as well.
```
bin2ml generate nlp --path file.so_reg.json --instruction-type esil --data-out-path . --output-format single
thread 'main' panicked at src/files.rs:295:18:
Unable to load and desearlize JSON: ()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

bin2ml generate nlp --path file.so_reg.json --instruction-type esil --data-out-path . --output-format funcstring
thread 'main' panicked at src/files.rs:208:18:
Unable to load and desearilize JSON: ()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by br0kej** [comment]
Thank you again for the great feedback @cielonet. I will add some checks to the CLI 👍🏼

**Comment by br0kej** [comment]
@cielonet , I have addd some initial validation to the CLI on `dev`. If you have a mo, could you give it a try?

**Comment by cielonet** [comment]
Hey for the most part your changes worked well. I did find another little one nothing major. Otherwise thank you for the fixes...

`bin2ml extract --mode cfg --fpath ../binary --output-dir thisfilefolderdoesnotexists`
```thread 'main' panicked at src/extract.rs:543:45:
Unable to create file!: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)```

**Comment by br0kej** [comment]
> Hey for the most part your changes worked well. I did find another little one nothing major. Otherwise thank you for the fixes...
> 
> `bin2ml extract --mode cfg --fpath ../binary --output-dir thisfilefolderdoesnotexists`
> ```thread 'main' panicked at src/extract.rs:543:45:
> Unable to create file!: Os { code: 2, kind: NotFound, message: "No such file or directory" }
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Aborted (core dumped)```
> 

I think this behaviour is correct. I didn't want to create repos that could be typos etc automatically and instead assume the directory is created beforehand. Does that make sense for your use case?

**Comment by cielonet** [comment]
> > Hey for the most part your changes worked well. I did find another little one nothing major. Otherwise thank you for the fixes...
> > `bin2ml extract --mode cfg --fpath ../binary --output-dir thisfilefolderdoesnotexists`
> > ```
> > Unable to create file!: Os { code: 2, kind: NotFound, message: "No such file or directory" }
> > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > Aborted (core dumped)```
> > ```
> 
> I think this behaviour is correct. I didn't want to create repos that could be typos etc automatically and instead assume the directory is created beforehand. Does that make sense for your use case?

I am no expert in rust. Far from it, but I believe there is a way to catch these types of errors more elegantly so that *core dumped* isn't outputed using match.
```
match file_result {
        Ok(_) => {
            println!("File created successfully!");
            Ok(())
        }
        Err(err) => {
            if err.kind() == io::ErrorKind::NotFound {
                Err(io::Error::new(
                    io::ErrorKind::NotFound,
                    "The specified directory does not exist.",
                ))
            } else {
                Err(err)
```

This is just the QA guy in me :-). Thank you for looking over it.

**Comment by cielonet** [comment]
Sorry I feel like I'm spamming now :-( --- I tried using `dedup` this morning and even with valid expected data I was getting an error msg.

```
# using expected file
root@ae6a62491516:/app# touch out.json
███████████████████████████████████████████ 1/1
root@ae6a62491516:/app# bin2ml dedup esil --filename file_cfg-efs.json --output-path out.json 
thread 'main' panicked at src/dedup.rs:282:45:
Failed to create writer: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

# wrong type of json file
root@ae6a62491516:/app# bin2ml dedup esil --filename file_cfg.json --output-path out.json 
███████████████████████████████████████████ 1/1
thread 'main' panicked at src/dedup.rs:75:14:
Unable to load function data from file_cfg.json: Error("invalid type: sequence, expected a map", line: 1, column: 0)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
root@ae6a62491516:/app# ls
file_cfg-efs.json  file_cfg.json  out.json
```

**Comment by br0kej** [comment]
It's not spam! All of these are valid. I'll look to fix the new one too!

**Comment by br0kej** [comment]
@cielonet, I think I've fixed all of these on `main`. Could you check them out?

**Comment by br0kej** [comment]
Assuming everything is all good! 👍🏼
